<%@ Page Language="VB" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="frmOC_Sum_Pic_Zoom.aspx.vb" Inherits="frmOC_Sum_Pic" Title="Documentos Soporte" %>

<%@ Register Assembly="DevExpress.Web.v16.1, Version=16.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web" TagPrefix="dx" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphMenu" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphContenido" runat="Server">
    <table style="border-style: solid; border-width: thin; width: 80%; height: 100%;" cellpadding="0" cellspacing="0">
        <tr>
            <td style="width: 100%; height: 1%" align="left" valign="top">
                <table style="width: 100%; height: 100%;" cellpadding="0" cellspacing="0">
                    <tr>
                        <td style="width: 100%; height: 100%" align="center" valign="top" bgcolor="#339966">
                            <asp:Button ID="btnRegresar" runat="server" BackColor="Gray" BorderStyle="Outset" ForeColor="White"
                                Text="Cerrar" Height="30px" BorderColor="#404040" CssClass="Estilo_Boton" Width="80px" /></td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td style="width: 100%; height: 20px" align="center" valign="top"></td>
        </tr>
        <tr>
            <td style="width: 100%; height: 99%" align="left" valign="top">
                <table style="width: 100%; height: 100%" cellspacing="0" cellpadding="0">
                    <tbody>
                        <tr>
                            <td style="width: 100%; height: 20px" valign="top" align="center"></td>
                        </tr>
                        <tr>
                            <td style="width: 100%; height: 99%" valign="top" align="center">
                                <table style="width: 100%; height: 100%" cellspacing="0" cellpadding="0">
                                    <tbody>
                                        <tr>
                                            <td style="width: 100%; height: 100%" valign="top" align="center">
                                                <dx:ASPxImageZoom ID="ASPxImageZoom1" runat="server" ClientInstanceName="iz" AssociatedImageZoomNavigatorID="ASPxImageZoomNavigator1" />

                                                <dx:ASPxImageZoomNavigator ID="ASPxImageZoomNavigator1" runat="server" ClientInstanceName="izn">
                                                    <SettingsAutoGeneratedImages ImageHeight="350" ImageWidth="350" LargeImageHeight="900" LargeImageWidth="900"
                                                        ThumbnailWidth="75" ThumbnailHeight="75" />
                                                    <Styles>
                                                        <Thumbnail ImageHeight="75" ImageWidth="75" />
                                                    </Styles>
                                                </dx:ASPxImageZoomNavigator>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </table>
</asp:Content>

